name: Build Tiny11 ISO

on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Windows 11 ISO
      run: |
        Invoke-WebRequest -Uri "https://software-download.microsoft.com/pr/Win11_23H2_English_x64.iso" -OutFile "Win11.iso"
      shell: pwsh

    - name: Mount ISO
      run: |
        $mountResult = Mount-DiskImage -ImagePath "$PWD\Win11.iso" -PassThru
        $driveLetter = ($mountResult | Get-Volume).DriveLetter
        echo "ISO_DRIVE=$driveLetter" >> $env:GITHUB_ENV
      shell: pwsh

    - name: Run Tiny11Builder Script
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        .\tiny11maker.ps1 -ISO $env:ISO_DRIVE -SCRATCH C
      shell: pwsh

    - name: Upload ISO Artifact
      uses: actions/upload-artifact@v3
      with:
        name: tiny11.iso
        path: ./tiny11.iso
