name: Build Tiny11 ISO

on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Windows 11 ISO
      run: |
        Invoke-WebRequest -Uri "https://software.download.prss.microsoft.com/dbazure/Win11_24H2_EnglishInternational_x64.iso?t=dcc379aa-0cfc-4152-9baf-a5f778424bd8&P1=1759230140&P2=601&P3=2&P4=CuW3sUh8QYNfFyUe%2fSXjgWoPs5sZMtQCW862oS4M6hwbtq6EaGFiqJHFdh4%2bqByUWH2p5hBAf18fb7dqzLBkxI%2bXTDoKXDEwbtFRq0lqUuqwbl0KfO68focD3Y9y1RDnHRTbp2PCT1kSyCIPgFniMycuaRzjhe%2bmTLjazZXcb74x2%2fVj3X1jeZc25%2fpIuNl49SRHksQd8fnxLLo1HfOTLqHp8Es%2b8Zuu2o99EhbD%2b0yvgrYPwvg64tXQQg7wrVJtim4ZS5OIs6imezGdWHLLW%2f4yrDh8V187so%2fGtQM3zBaCsC3jIRBcKogWh%2fqc547sivGpMdT2Gqg8BqSPsqW1Iw%3d%3d" -OutFile "Win11.iso"
      shell: pwsh

    - name: Mount ISO
      run: |
        $mountResult = Mount-DiskImage -ImagePath "$PWD\Win11.iso" -PassThru
        $driveLetter = ($mountResult | Get-Volume).DriveLetter
        echo "ISO_DRIVE=$driveLetter" >> $env:GITHUB_ENV
      shell: powershell

    - name: Run Tiny11Builder Script
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        .\tiny11maker.ps1 -ISO $env:ISO_DRIVE -SCRATCH C
      shell: powershell

    - name: Upload ISO Artifact
      uses: actions/upload-artifact@v4
      with:
        name: tiny11.iso
        path: ./tiny11.iso
